name: DuelCustom
version: 1.0.4_CUSTOM_BETA
main: com.gmail.gogobebe2.duel.Duel
description: A pvp duel plugin for 1v1 fights.
author: William Bryant
website: gogobebe2@gmail.com

commands:
    duel:
        usage: /duel <player>, /duel stats or /duel accept
        description: Duel a player in a 1v1 fight.
        permissions:
            duel.*:
                 description: Gives access to /duel
                 default: op
    leaveduel:
        usage: /duelleave if in a duel.
        description: Leave the duel.
