name: DuelCustom
version: 1.0.2_CUSTOM_BETA
main: com.gmail.gogobebe2.duel.Duel
description: A pvp duel plugin for 1v1 fights.
author: gogobebe2
website: gogobebe2@gmail.com

commands:
    duel:
        usage: /<command>
        description: Duel a player in a 1v1 fight.
        permissions:
            duel.*:
                 description: Gives access to /duel
                 default: op
    leaveduel:
        usage: /<command>
        description: Leave the duel.
